export const ConfigEnum = {
  DB_URL: 'DB_URL',
  DB_NAME: 'DB_NAME',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_DATABASE: 'DB_DATABASE',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_SYNC: 'DB_SYNC',
};
